import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { dirname } from "node:path";
import { parse as parseJsonc } from "jsonc-parser";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const INSTALL_SCRIPT = join(ROOT, "scripts", "install.mjs");

// Every run gets an isolated AGENT_TOOLS_HOME so tests never write into the
// real ~/.agent-tools; deps installation is skipped (covered by real installs).
const FALLBACK_HOME = mkdtempSync(join(tmpdir(), "at-vision-install-home-"));

function runInstall(args, env = {}) {
  const result = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env: {
      ...process.env,
      AGENT_TOOLS_HOME: FALLBACK_HOME,
      ...env,
    },
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return result;
}

function tmp() {
  return mkdtempSync(join(tmpdir(), "at-vision-install-"));
}

function runtimeServerPath(home) {
  return join(home, "dist", "vision", "mcp-server.mjs").replace(/\\/g, "/");
}

// ---- pi ----

test("pi vision installs a native extension stub, runtime, and skill", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const agentDir = join(dir, "pi-agent");
  const args = ["vision", "-a", "pi", "--pi-agent-dir", agentDir];
  const env = { AGENT_TOOLS_HOME: home };

  runInstall(args, env);
  const stub = join(agentDir, "extensions", "agent-tools-vision.js");
  const skill = join(agentDir, "skills", "at-vision", "SKILL.md");
  const extension = join(home, "dist", "vision", "pi-extension.mjs");
  assert.ok(existsSync(stub));
  assert.match(readFileSync(stub, "utf8"), /Generated by agent-tools installer/);
  assert.match(readFileSync(stub, "utf8"), /pi-extension\.mjs/);
  assert.ok(existsSync(extension));
  assert.ok(existsSync(skill));

  runInstall(args, env);
  runInstall([...args, "--uninstall"], env);
  assert.ok(!existsSync(stub));
  assert.ok(!existsSync(join(agentDir, "skills", "at-vision")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});

test("pi vision preserves an unmanaged same-name extension", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const agentDir = join(dir, "pi-agent");
  const stub = join(agentDir, "extensions", "agent-tools-vision.js");
  mkdirSync(join(agentDir, "extensions"), { recursive: true });
  writeFileSync(stub, "export default () => {};\n");
  const args = ["vision", "-a", "pi", "--pi-agent-dir", agentDir];
  const env = { ...process.env, AGENT_TOOLS_HOME: home };

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env,
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.match(install.stderr, /Refusing to overwrite existing unmanaged Pi extension/);
  assert.equal(readFileSync(stub, "utf8"), "export default () => {};\n");

  runInstall([...args, "--uninstall"], env);
  assert.equal(readFileSync(stub, "utf8"), "export default () => {};\n");
});

// ---- zcode ----

test("zcode vision manages native MCP config and the user skill", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const config = join(dir, "zcode", "cli", "config.json");
  const skillsDir = join(dir, "zcode", "skills");
  mkdirSync(join(dir, "zcode", "cli"), { recursive: true });
  writeFileSync(
    config,
    '{\n  // keep this comment\n  "theme": "dark",\n  "mcp": { "servers": { "other": { "command": "keep" } } }\n}\n'
  );
  const args = [
    "vision", "-a", "zcode",
    "--zcode-config", config,
    "--zcode-skills-dir", skillsDir,
  ];
  const env = { AGENT_TOOLS_HOME: home };

  runInstall(args, env);
  let text = readFileSync(config, "utf8");
  let cfg = parseJsonc(text);
  assert.match(text, /keep this comment/);
  assert.equal(cfg.theme, "dark");
  assert.equal(cfg.mcp.servers.other.command, "keep");
  assert.deepEqual(cfg.mcp.servers["agent-tools-vision"], {
    command: "node",
    args: [runtimeServerPath(home)],
    env: {},
  });
  assert.ok(existsSync(join(skillsDir, "at-vision", "SKILL.md")));

  runInstall(args, env);
  runInstall([...args, "--uninstall"], env);
  text = readFileSync(config, "utf8");
  cfg = parseJsonc(text);
  assert.match(text, /keep this comment/);
  assert.equal(cfg.mcp.servers["agent-tools-vision"], undefined);
  assert.equal(cfg.mcp.servers.other.command, "keep");
  assert.ok(!existsSync(join(skillsDir, "at-vision")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});

test("zcode vision preserves an unmanaged same-name MCP entry", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const config = join(dir, "config.json");
  const manual = { command: "node", args: ["custom-server.mjs"] };
  writeFileSync(config, JSON.stringify({ mcp: { servers: { "agent-tools-vision": manual } } }));
  const args = [
    "vision", "-a", "zcode",
    "--zcode-config", config,
    "--zcode-skills-dir", join(dir, "skills"),
  ];
  const env = { ...process.env, AGENT_TOOLS_HOME: home };

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env,
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.deepEqual(JSON.parse(readFileSync(config, "utf8")).mcp.servers["agent-tools-vision"], manual);

  runInstall([...args, "--uninstall"], env);
  assert.deepEqual(JSON.parse(readFileSync(config, "utf8")).mcp.servers["agent-tools-vision"], manual);
});

// ---- claude ----

test("claude vision install/uninstall manages ~/.claude.json, the runtime, and the skill", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const claudeJson = join(dir, "claude.json");
  const skillsDir = join(dir, "skills");
  writeFileSync(
    claudeJson,
    JSON.stringify({ mcpServers: { other: { command: "keep-me" } }, someState: 42 })
  );
  const args = ["vision", "-a", "claude", "--claude-json", claudeJson, "--claude-skills-dir", skillsDir];
  const env = { AGENT_TOOLS_HOME: home };

  runInstall(args, env);
  let cfg = JSON.parse(readFileSync(claudeJson, "utf8"));
  assert.deepEqual(cfg.mcpServers["agent-tools-vision"], {
    type: "stdio",
    command: "node",
    args: [runtimeServerPath(home)],
  });
  assert.equal(cfg.mcpServers.other.command, "keep-me");
  assert.equal(cfg.someState, 42);
  assert.ok(existsSync(join(skillsDir, "at-vision", "SKILL.md")));
  assert.match(
    readFileSync(join(skillsDir, "at-vision", "SKILL.md"), "utf8"),
    /callable MCP tool, not an MCP resource/
  );
  assert.ok(!existsSync(join(skillsDir, "at-vision", ".agent-tools-managed.json")));
  const installState = JSON.parse(readFileSync(join(home, "install-state.json"), "utf8"));
  assert.equal(Object.values(installState.artifacts)[0].capability, "vision");
  // Runtime copied into AGENT_TOOLS_HOME with a deps manifest.
  assert.ok(existsSync(join(home, "dist", "vision", "mcp-server.mjs")));
  assert.ok(existsSync(join(home, "dist", "vision", "cli.mjs")));
  const runtimeMeta = JSON.parse(readFileSync(join(home, "dist", "vision", "runtime.json"), "utf8"));
  assert.equal(runtimeMeta.owner, "@kairyou/agent-tools");
  assert.ok(!existsSync(join(home, "dist", "vision", "node_modules")));

  // Reinstall is idempotent.
  runInstall(args, env);
  const again = JSON.parse(readFileSync(claudeJson, "utf8"));
  assert.deepEqual(again, cfg);

  runInstall([...args, "--uninstall"], env);
  cfg = JSON.parse(readFileSync(claudeJson, "utf8"));
  assert.equal(cfg.mcpServers["agent-tools-vision"], undefined);
  assert.equal(cfg.mcpServers.other.command, "keep-me");
  assert.equal(cfg.someState, 42);
  assert.ok(!existsSync(join(skillsDir, "at-vision")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});

test("claude vision preserves an unmanaged same-name MCP entry", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const claudeJson = join(dir, "claude.json");
  const manual = { type: "stdio", command: "node", args: ["custom-server.mjs"] };
  writeFileSync(claudeJson, JSON.stringify({ mcpServers: { "agent-tools-vision": manual } }));
  const args = [
    "vision", "-a", "claude",
    "--claude-json", claudeJson,
    "--claude-skills-dir", join(dir, "skills"),
  ];

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env: { ...process.env, AGENT_TOOLS_HOME: home },
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.deepEqual(JSON.parse(readFileSync(claudeJson, "utf8")).mcpServers["agent-tools-vision"], manual);

  runInstall([...args, "--uninstall"]);
  assert.deepEqual(JSON.parse(readFileSync(claudeJson, "utf8")).mcpServers["agent-tools-vision"], manual);
});

// ---- codex ----

test("codex vision manages a marker block in config.toml without touching other content", () => {
  const dir = tmp();
  const codexConfig = join(dir, "config.toml");
  const skillsDir = join(dir, "skills");
  const original = 'model = "gpt-5"\n\n[mcp_servers.existing]\ncommand = "keep"\n';
  writeFileSync(codexConfig, original);
  const args = ["vision", "-a", "codex", "--codex-config", codexConfig, "--codex-skills-dir", skillsDir];

  runInstall(args);
  let text = readFileSync(codexConfig, "utf8");
  assert.match(text, /model = "gpt-5"/);
  assert.match(text, /\[mcp_servers\.existing\]/);
  assert.match(text, /# >>> agent-tools vision >>>/);
  assert.match(text, /\[mcp_servers\.agent-tools-vision\]/);
  assert.match(text, /dist[/\\]vision[/\\]mcp-server\.mjs/);
  assert.ok(existsSync(join(skillsDir, "at-vision", "SKILL.md")));

  // Reinstall does not duplicate the block.
  runInstall(args);
  text = readFileSync(codexConfig, "utf8");
  assert.equal(text.match(/agent-tools vision >>>/g).length, 1);

  runInstall([...args, "--uninstall"]);
  text = readFileSync(codexConfig, "utf8");
  assert.doesNotMatch(text, /agent-tools-vision/);
  assert.match(text, /model = "gpt-5"/);
  assert.match(text, /\[mcp_servers\.existing\]/);
  assert.ok(!existsSync(join(skillsDir, "at-vision")));
});

test("codex vision installs the skill into ~/.agents/skills by default", () => {
  const dir = tmp();
  const codexConfig = join(dir, "config.toml");
  const skill = join(dir, ".agents", "skills", "at-vision", "SKILL.md");
  const args = ["vision", "-a", "codex", "--codex-config", codexConfig];
  const env = { HOME: dir, USERPROFILE: dir };

  runInstall(args, env);
  assert.ok(existsSync(skill));

  runInstall([...args, "--uninstall"], env);
  assert.ok(!existsSync(join(dir, ".agents", "skills", "at-vision")));
});

test("vision refuses to overwrite an unowned skill and preserves it on uninstall", () => {
  const dir = tmp();
  const codexConfig = join(dir, "config.toml");
  const skillsDir = join(dir, "skills");
  const skillDir = join(skillsDir, "at-vision");
  const manual = join(skillDir, "manual.txt");
  mkdirSync(skillDir, { recursive: true });
  writeFileSync(manual, "user-owned\n");
  const args = [
    "vision", "-a", "codex",
    "--codex-config", codexConfig,
    "--codex-skills-dir", skillsDir,
  ];
  const env = {
    ...process.env,
    AGENT_TOOLS_HOME: join(dir, "agent-tools-home"),
  };

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env,
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.match(install.stderr, /Refusing to overwrite existing unowned skill directory/);
  assert.equal(readFileSync(manual, "utf8"), "user-owned\n");

  runInstall([...args, "--uninstall"], env);
  assert.equal(readFileSync(manual, "utf8"), "user-owned\n");
});

test("vision skill embeds the installed CLI path for a custom runtime home", () => {
  const dir = tmp();
  const home = join(dir, "custom runtime home");
  const skillsDir = join(dir, "skills");
  runInstall([
    "vision", "-a", "codex",
    "--codex-config", join(dir, "config.toml"),
    "--codex-skills-dir", skillsDir,
  ], { AGENT_TOOLS_HOME: home });

  const skill = readFileSync(join(skillsDir, "at-vision", "SKILL.md"), "utf8");
  const expected = join(home, "dist", "vision", "cli.mjs").replace(/\\/g, "/");
  assert.match(skill, new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.doesNotMatch(skill, /\{\{VISION_CLI_PATH\}\}/);
});

test("vision update atomically replaces the bundled runtime", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const skillsDir = join(dir, "skills");
  const args = [
    "vision", "-a", "codex",
    "--codex-config", join(dir, "config.toml"),
    "--codex-skills-dir", skillsDir,
  ];
  runInstall(args, { AGENT_TOOLS_HOME: home });

  const staleRuntime = join(home, "dist", "vision", "removed-in-update.mjs");
  const staleSkill = join(skillsDir, "at-vision", "removed-in-update.md");
  for (const file of [staleRuntime, staleSkill]) {
    mkdirSync(join(file, ".."), { recursive: true });
    writeFileSync(file, "stale\n");
  }

  runInstall(args, { AGENT_TOOLS_HOME: home });
  assert.ok(!existsSync(staleRuntime));
  assert.ok(!existsSync(staleSkill));
  assert.ok(existsSync(join(home, "dist", "vision", "mcp-server.mjs")));
});

test("vision runtime rollback preserves the previous install when the atomic swap fails", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const args = [
    "vision", "-a", "codex",
    "--codex-config", join(dir, "config.toml"),
    "--codex-skills-dir", join(dir, "skills"),
  ];
  runInstall(args, { AGENT_TOOLS_HOME: home });
  const sentinel = join(home, "dist", "vision", "previous-runtime.txt");
  writeFileSync(sentinel, "still working\n");

  const failed = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env: {
      ...process.env,
      AGENT_TOOLS_HOME: home,
      AGENT_TOOLS_VISION_TEST_FAIL_SWAP: "1",
    },
    encoding: "utf8",
  });
  assert.notEqual(failed.status, 0);
  assert.equal(readFileSync(sentinel, "utf8"), "still working\n");
  assert.ok(existsSync(join(home, "dist", "vision", "mcp-server.mjs")));
});

test("codex vision refuses to install over a manually configured same-name table", () => {
  const dir = tmp();
  const codexConfig = join(dir, "config.toml");
  const manual = '[mcp_servers.agent-tools-vision]\ncommand = "my-own-thing"\n';
  writeFileSync(codexConfig, manual);
  const result = spawnSync(
    process.execPath,
    [
      INSTALL_SCRIPT, "vision", "-a", "codex",
      "--codex-config", codexConfig,
      "--codex-skills-dir", join(dir, "skills"),
    ],
    {
      cwd: ROOT,
      env: { ...process.env, AGENT_TOOLS_HOME: FALLBACK_HOME },
      encoding: "utf8",
    }
  );
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /not\s+written by this installer/);
  assert.equal(readFileSync(codexConfig, "utf8"), manual);
});

test("codex vision creates config.toml when absent and empties it on uninstall", () => {
  const dir = tmp();
  const codexConfig = join(dir, "config.toml");
  const args = [
    "vision", "-a", "codex",
    "--codex-config", codexConfig,
    "--codex-skills-dir", join(dir, "skills"),
  ];
  runInstall(args);
  assert.match(readFileSync(codexConfig, "utf8"), /agent-tools-vision/);
  runInstall([...args, "--uninstall"]);
  assert.equal(readFileSync(codexConfig, "utf8").trim(), "");
});

// ---- opencode ----

test("opencode vision edits opencode.json in place, preserving comments", () => {
  const dir = tmp();
  const file = join(dir, "opencode.json");
  writeFileSync(
    file,
    '{\n  // user comment stays\n  "theme": "dark",\n  "mcp": {\n    "other": { "type": "local", "command": ["keep"] }\n  }\n}\n'
  );
  const home = join(dir, "agent-tools-home");
  const args = ["vision", "-a", "opencode", "--opencode-config-dir", dir];

  runInstall(args, { AGENT_TOOLS_HOME: home });
  let text = readFileSync(file, "utf8");
  assert.match(text, /\/\/ user comment stays/);
  let cfg = parseJsonc(text);
  assert.deepEqual(cfg.mcp["agent-tools-vision"], {
    type: "local",
    command: ["node", runtimeServerPath(home)],
    enabled: true,
  });
  assert.deepEqual(cfg.mcp.other.command, ["keep"]);
  assert.equal(cfg.theme, "dark");
  assert.ok(existsSync(join(dir, "skills", "at-vision", "SKILL.md")));

  runInstall([...args, "--uninstall"], { AGENT_TOOLS_HOME: home });
  text = readFileSync(file, "utf8");
  assert.match(text, /\/\/ user comment stays/);
  cfg = parseJsonc(text);
  assert.equal(cfg.mcp["agent-tools-vision"], undefined);
  assert.deepEqual(cfg.mcp.other.command, ["keep"]);
  assert.ok(!existsSync(join(dir, "skills", "at-vision")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});

test("opencode vision preserves an unmanaged same-name MCP entry", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const file = join(dir, "opencode.json");
  const manual = { type: "local", command: ["node", "custom-server.mjs"], enabled: true };
  writeFileSync(file, JSON.stringify({ mcp: { "agent-tools-vision": manual } }));
  const args = ["vision", "-a", "opencode", "--opencode-config-dir", dir];

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env: { ...process.env, AGENT_TOOLS_HOME: home },
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.deepEqual(parseJsonc(readFileSync(file, "utf8")).mcp["agent-tools-vision"], manual);

  runInstall([...args, "--uninstall"], { AGENT_TOOLS_HOME: home });
  assert.deepEqual(parseJsonc(readFileSync(file, "utf8")).mcp["agent-tools-vision"], manual);
});

// ---- deepseek harness ----

test("dsh vision manages an official MCP client row and the user skill", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const dshHome = join(dir, "dsh-home");
  const patchFile = join(dshHome, "cordis.patch.yml");
  mkdirSync(dshHome, { recursive: true });
  const original = [
    "- insert:",
    "    - id: keep-this-row",
    "      name: '@example/plugin'",
    "",
  ].join("\n");
  writeFileSync(patchFile, original);
  const args = ["vision", "-a", "dsh", "--dsh-home", dshHome];
  const env = { AGENT_TOOLS_HOME: home };

  runInstall(args, env);
  let text = readFileSync(patchFile, "utf8");
  assert.match(text, /id: keep-this-row/);
  assert.match(text, /# >>> agent-tools vision >>>/);
  assert.match(text, /name: '@deepseek-ai\/dsh-mcp-client'/);
  assert.match(text, /serverName: agent-tools-vision/);
  assert.match(text, new RegExp(runtimeServerPath(home).replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.ok(existsSync(join(dshHome, "skills", "at-vision", "SKILL.md")));

  runInstall(args, env);
  assert.equal(readFileSync(patchFile, "utf8").match(/agent-tools vision >>>/g).length, 1);

  runInstall([...args, "--uninstall"], env);
  text = readFileSync(patchFile, "utf8");
  assert.equal(text.trim(), original.trim());
  assert.ok(!existsSync(join(dshHome, "skills", "at-vision")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});

test("dsh vision converts an empty patch array and restores it on uninstall", () => {
  const dir = tmp();
  const dshHome = join(dir, "dsh-home");
  const patchFile = join(dshHome, "cordis.patch.yml");
  const args = ["vision", "-a", "dsh", "--dsh-home", dshHome];

  runInstall(args, { AGENT_TOOLS_HOME: join(dir, "agent-tools-home") });
  assert.doesNotMatch(readFileSync(patchFile, "utf8"), /^\[\]/m);
  runInstall([...args, "--uninstall"], { AGENT_TOOLS_HOME: join(dir, "agent-tools-home") });
  assert.equal(readFileSync(patchFile, "utf8"), "[]\n");
});

test("dsh vision refuses an unmanaged conflicting Cordis row", () => {
  const dir = tmp();
  const dshHome = join(dir, "dsh-home");
  const patchFile = join(dshHome, "cordis.patch.yml");
  mkdirSync(dshHome, { recursive: true });
  const manual = "- insert:\n    - id: agent-tools-vision\n      name: '@example/custom'\n";
  writeFileSync(patchFile, manual);
  const args = ["vision", "-a", "dsh", "--dsh-home", dshHome];
  const env = { ...process.env, AGENT_TOOLS_HOME: join(dir, "agent-tools-home") };

  const install = spawnSync(process.execPath, [INSTALL_SCRIPT, ...args], {
    cwd: ROOT,
    env,
    encoding: "utf8",
  });
  assert.notEqual(install.status, 0);
  assert.match(install.stderr, /existing unmanaged agent-tools-vision Cordis row/);
  assert.equal(readFileSync(patchFile, "utf8"), manual);

  runInstall([...args, "--uninstall"], env);
  assert.equal(readFileSync(patchFile, "utf8"), manual);
});

// ---- combined ----

test("one command installs vision for every supported agent", () => {
  const dir = tmp();
  const result = runInstall([
    "vision", "-a", "codex", "claude", "opencode", "pi", "zcode", "dsh",
    "--claude-json", join(dir, "claude.json"),
    "--claude-skills-dir", join(dir, "claude-skills"),
    "--codex-config", join(dir, "config.toml"),
    "--codex-skills-dir", join(dir, "codex-skills"),
    "--opencode-config-dir", join(dir, "opencode"),
    "--pi-agent-dir", join(dir, "pi-agent"),
    "--zcode-config", join(dir, "zcode", "cli", "config.json"),
    "--zcode-skills-dir", join(dir, "zcode", "skills"),
    "--dsh-home", join(dir, "dsh-home"),
  ], { AGENT_TOOLS_HOME: join(dir, "agent-tools-home") });
  assert.match(result.stdout, /claude vision:/);
  assert.match(result.stdout, /codex vision:/);
  assert.match(result.stdout, /opencode vision:/);
  assert.match(result.stdout, /pi vision:/);
  assert.match(result.stdout, /zcode vision:/);
  assert.match(result.stdout, /dsh vision:/);
  assert.ok(existsSync(join(dir, "claude.json")));
  assert.ok(existsSync(join(dir, "config.toml")));
  assert.ok(existsSync(join(dir, "opencode", "opencode.json")));
  assert.ok(existsSync(join(dir, "pi-agent", "extensions", "agent-tools-vision.js")));
  assert.ok(existsSync(join(dir, "zcode", "cli", "config.json")));
  assert.ok(existsSync(join(dir, "dsh-home", "cordis.patch.yml")));
});

test("vision uninstall keeps the shared runtime until its last agent reference is removed", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const codexConfig = join(dir, "config.toml");
  const claudeJson = join(dir, "claude.json");
  const common = [
    "--codex-config", codexConfig,
    "--codex-skills-dir", join(dir, "codex-skills"),
    "--claude-json", claudeJson,
    "--claude-skills-dir", join(dir, "claude-skills"),
  ];
  const env = { AGENT_TOOLS_HOME: home };

  runInstall(["vision", "-a", "codex", "claude", ...common], env);
  mkdirSync(join(home, "cache"), { recursive: true });
  writeFileSync(join(home, "cache", "vision-rate-limit.json"), "{}\n");
  runInstall(["vision", "-a", "claude", ...common, "--uninstall"], env);
  assert.ok(existsSync(join(home, "dist", "vision")));
  assert.ok(existsSync(join(home, "cache", "vision-rate-limit.json")));

  runInstall(["vision", "-a", "codex", ...common, "--uninstall"], env);
  assert.ok(!existsSync(join(home, "dist", "vision")));
  assert.ok(!existsSync(join(home, "cache", "vision-rate-limit.json")));
});

test("dry-run writes nothing", () => {
  const dir = tmp();
  const home = join(dir, "agent-tools-home");
  const claudeJson = join(dir, "claude.json");
  runInstall([
    "vision", "-a", "claude",
    "--claude-json", claudeJson,
    "--claude-skills-dir", join(dir, "skills"),
    "--dry-run",
  ], { AGENT_TOOLS_HOME: home });
  assert.ok(!existsSync(claudeJson));
  assert.ok(!existsSync(join(dir, "skills")));
  assert.ok(!existsSync(join(home, "dist", "vision")));
});
